sonar.projectKey=sga_cliente_calendario_academico_mf
sonar.projectName=sga_cliente_calendario_academico_mf
sonar.projectVersion=1.0

sonar.sources=./
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.scss
#sonar.tests=src
#sonar.test.inclusions=**/*.spec.ts

sonar.sourceEncoding=UTF-8
