
export let FORM_PERIODO = {
    titulo: 'Periodo',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Periodo',
    campos: [

    {
        etiqueta: 'input',
        claseGrid: 'form-col2',
        nombre: 'Year',
        label_i18n: 'ano',
        placeholder_i18n: 'ano',
        requerido: true,
        tipo: 'number',
        minimo: '2000',
        maximolog: '2999',
    },
    {
        etiqueta: 'input',
        claseGrid: 'form-col2',
        nombre: 'Ciclo',
        label_i18n: 'periodo',
        placeholder_i18n: 'periodo',
        requerido: true,
        tipo: 'number',
        minimo: '1',
        maximolog: '9',
    },
    {
        etiqueta: 'input',
        claseGrid: 'form-col1',
        nombre: 'InicioVigencia',
        label_i18n: 'fecha_inicio',
        placeholder_i18n: 'fecha_inicio',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'input',
        claseGrid: 'form-col1',
        nombre: 'FinVigencia',
        label_i18n: 'fecha_fin',
        placeholder_i18n: 'fecha_fin',
        requerido: true,
        tipo: 'date',
    },
/*     
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Descripcion',
        label_i18n: 'descripcion',
        placeholder_i18n: 'descripcion',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'CodigoAbreviacion',
        label_i18n: 'codigo_abreviacion',
        placeholder_i18n: 'codigo_abreviacion',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Activo',
        label_i18n: 'activo',
        placeholder_i18n: 'activo',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'NumeroOrden',
        label_i18n: 'numero_orden',
        placeholder_i18n: 'numero_orden',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'TipoPeriodo',
        label_i18n: 'tipo_periodo',
        placeholder_i18n: 'tipo_periodo',
        requerido: true,
        tipo: 'TipoPeriodo',
        key: 'Nombre',
        opciones: [],
    },
*/
    ],
}
